name: Generate Executable
on:
  workflow_dispatch:
  release:
    types: [ published ]
jobs:
  build:
    name: Person-api on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.1.0'
          java-version: '17'
          components: 'native-image'

      - name: Cache Maven
        uses: actions/cache@v3.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build person-api
        run: ./mvnw -Pnative -DskipTests clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-${{ matrix.os }}
          path: application/target/application